config/routes.rb
Omaha::Application.routes.draw do

  get "pages/searchusers"
  get "pages/foundusers"
  get "pages/runquery"
  get "pages/foundbyquery"
  get "pages/partyid"

  root :to => 'pages#searchusers'

  match '/search', :to => 'pages#searchusers'
  match '/found', :to => 'pages#foundusers'
  match '/runquery', :to => 'pages#runquery'
  match '/foundbyquery', :to => 'pages#foundbyquery'
  match '/partyid', :to => 'pages#partyid'
  match '/entitlements', :to => 'pages#entitlements'
  match '/entitlementsfile', :to => 'pages#entitlementsfile'

end

app/models/entitlements.rb
require 'json'
require 'net/http'
require 'csv'

class Entitlements

  def self.get_entitlements(partyid)

    base_url = "http://e04-identity.mcs.bskyb.com/mcs-identity/jersey/entitlements/"
    url = URI("#{base_url}#{partyid}")
    resp = Net::HTTP.get_response(url)
    data = resp.body

    # we convert the returned JSON data to native Ruby
    # data structure - a hash
    response = JSON.parse(data)

    user_entitlement = ''

    if !response['entitlements'].empty?
      response['entitlements'].each { |ent|
        user_entitlement = user_entitlement + "<item>"+ent+"</item>"
      }
      result = {response['partyId'] => user_entitlement}
    end


    #if result has status then check error code
    if response.has_key? 'status'
      case response['status']['code']
        when code = '2008' then
          result = {response['partyId'] => "[CODE=#{code}] Customer\'s subscription status with PartyID = #{partyid} is blocked"}
        when code = '2018' then
          result = {response['partyId'] => "[CODE=#{code}] Customer with PartyID = #{partyid} has no entitlements but is otherwise legitimate"}
        when code = '2001' then
          result = {response['partyId'] => "[CODE=#{code}] Customer with PartyID = #{partyid} was not recognised"}
      end
    end


    # if the hash has 'Error' as a key, we raise an error
    if response.has_key? 'Error'
      raise "web service error"
    end

    return result

  end

  def self.read_partyid
    CSV.read('partyid.txt').flatten!
  end

  def self.partyids_from_file(uploaded_file)
    # read PartyIds from uploaded file
    partyids = []
    uploaded_file.read.each_line { |line| partyids << line.gsub(/\n\r/, '') }

    # partyids.each { |e| e.gsub!(/\n\r/, '') }

    #just save uploaded file
    File.open(Rails.root.join('public', 'uploads', uploaded_file.original_filename), 'w') do |file|
      file.write(uploaded_file.read)
    end

    user_ent = []
    partyids.each { |p|
      user_ent << Entitlements.get_entitlements(p)
    }

    return user_ent
  end

end

#puts Entitlements.get_entitlements(13232530212841031374657)

#puts Entitlements.read_partyid

app/models/page.rb
class Page

 # attr_accessible :query

  #validates :query, presence: true

  def self.get_objects(db='IDMAN6T', username, date, ent)

    connect_to_db(db)

    query = generate_query(username, date, ent)

    started_seconds = Time.now.tv_sec

    resp = ActiveRecord::Base.connection.execute(query)

    time = Time.now.tv_sec-started_seconds

    return time, cursor_to_array(resp, true), query

  end


  def self.run_query (db='IDMAN6T', query)

    query.empty? ? (return time=0, "", "You don't have query") : query

    connect_to_db(db)

    started = Time.now.tv_sec

    resp = ActiveRecord::Base.connection.execute(query)

    time = Time.now.tv_sec-started

    return time, cursor_to_array(resp, true), query

  end


  def self.connect_to_db(db)
    case db
      when db = 'IDMAN6T' then
        ActiveRecord::Base.establish_connection :oracle_E04
      when db = 'IDMAN3T' then
        ActiveRecord::Base.establish_connection :oracle_E05
    end
  end

  def self.cursor_to_array(cursor, use_keys_as_header = false)
    result = []
    while r = cursor.fetch_hash
      result << r.keys if result.empty? && use_keys_as_header
      result << r.values
    end

    result
  end


  def self.generate_query(username, date, ent)
      # date.nil? ? (raise 'Date is nill!') : (puts date)
    #date.nil? ? ( date = '1-JAN-2012') : (date)

   query = "select distinct  sam.samprofileid, sam.username, crm.partyid, sam.registrationdate, ent.STARTDATE,
              ent.EXPIRYDATE, service.SERVICEENTMNTNAME

              from samprofiledata.samprofile sam, samprofiledata.crmprofile crm,
              samprofiledata.samprofile_service_entmnt ent, samprofiledata.service_entitlement service
              where sam.samprofileid = crm.samprofileid
              and sam.SAMPROFILEID = ent.SAMPROFILEID
              and ent.SERVICEENTMNTID = service.SERVICEENTMNTID

              and sam.registrationdate > '#{date}'
              and service.serviceentmntname like '#{ent}%'
              and sam.username like upper('#{username}%')
              and rownum < 100
              order by sam.registrationdate"



  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def searchusers
    @title = 'Search Users'
  end

  def foundusers
    @title = 'Found Users'
    username=params[:username]
    date=params[:date]
    entitlement=params[:entitlement]
    @db = params[:database]
    #puts "Date = #{params[:date]} "
    #puts "Entitlement = #{params[:entitlement]} "
    @time, @response, @query = Page.get_objects(@db, username, date, entitlement)

  end

  def runquery
    @title = 'Run Query'
  end

  def foundbyquery
    @title = 'From query'
    query = params[:query]
    @db = params[:database]

    @time, @response, @query = Page.run_query(@db, query)
  end


  def partyid
    @title = 'Get Entitlements'
  end

  def entitlements
    @title = 'Entitlements'
    if  !params[:partyid].empty?
      @user_ent = Entitlements.get_entitlements(params[:partyid])
    else
      render 'partyid'
    end


  end

  def entitlementsfile

    @title = 'Entitlements'

    #partyids = ['13232530212841031374657', '13232414127841031368648', '13232415347021031368669']
    #partyids = Entitlements.read_partyid

    uploaded_io = params[:upload_file]

    if  !params[:upload_file].nil?
      @user_ent = Entitlements.partyids_from_file(uploaded_io)
    else
      render 'partyid'
    end


  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_ent_error.html.erb
<h2>Some error</h2>

app/views/layouts/_header.html.erb
<div id="header">
  <%= link_to "Home", root_path, :class => "header", :text => "Home" %>
  <%= link_to "Run Query", runquery_path, :class => "header", :text =>"Run Query" %>
  <%= link_to "Get Entitlements", partyid_path, :class => "header", :text =>"Get Entitlements" %>
</div>

app/views/layouts/_noresult.html.erb
<div class='no_result'>
  <h4>Unfortunately, no records where found for your query!</h4>
</div>

app/views/layouts/_query.html.erb
<div class='query'>
  <%=@query%>
</div>

app/views/layouts/_queryinfo.html.erb
  <div class='query_info'>
    <h4>Database: <%= @db %></h4>
    <h4> <%= @time %> seconds</h4>
  </div>

app/views/layouts/_result_table.erb
<div class title="result">
  <h4> <%= @response.length-1 %> records found</h4>


  <table class="datagrid">

    <% @response.first.each do |header| %>

        <th> <%= header %>  </th>
    <% end %>
    <% @response.shift %>
    <% @response.each do |row| %>
        <tr>
          <% row.each do |column| %>
              <td><%= column %></td>
          <% end %>
        </tr>
    <% end %>
  </table>

</div>

app/views/layouts/_user_ent.erb
<div class="user_ent">
  <table class="datagrid">
    <tr>
      <th>PartyID</th>
      <th>Entitlements</th>
    </tr>

    <% @user_ent.each { |key, value| %>
    <tr>
      <td><%= key %></td>
      <td><%= value %></td>
    </tr>
    <% } %>
  </table>

  <%= puts @user_ent.inspect%>

</div>

app/views/layouts/_user_ent_file.html.erb
<div class="user_ent_file">
  <%=@party %>

  <table class="ent_datagrid">
    <tr>
      <th>PartyID</th>
      <th>Entitlements</th>
    </tr>


    <% @user_ent.each { |ent| %>

        <% ent.each { |key, value| %>
            <tr>
              <td><%= key %></td>
              <td><%= value %></td>
            </tr>
        <% } %>
    <% } %>


  </table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Omaha | <%= @title %></title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="main">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/entitlements.html.erb
<h2>Users entitlements</h2>

<%= render 'layouts/user_ent' %>

app/views/pages/entitlementsfile.html.erb
<h2>Users entitlements from file</h2>

<%= render 'layouts/user_ent_file' %>

app/views/pages/foundbyquery.html.erb
<h2>Users found</h2>
<div class='found_by_query_users'>

  <%= render 'layouts/queryinfo' %>
  <%= render 'layouts/query' %>

  <% if !@response.empty? %>
      <%= render 'layouts/result_table' %>
  <% else %>
      <%= render 'layouts/noresult' %>
  <% end %>


</div>

app/views/pages/foundusers.html.erb
<h2>Users found</h2>
<div class='found_users'>

  <%= render 'layouts/queryinfo' %>
  <%= render 'layouts/query' %>

  <% if !@response.empty? %>
      <%= render 'layouts/result_table' %>
  <% else %>
      <%= render 'layouts/noresult' %>
  <% end %>

</div>

app/views/pages/partyid.html.erb
<h2>Get user entitlements</h2>

<%= form_tag("/entitlements", :id => 'partyid-form', :method => "get") do %>

    <table class="form_table">

      <tr>
        <td><%= label_tag(:partyid, "Enter PartyID:") %></td>
        <td><%= text_field_tag(:partyid) %></td>
        <td><%= submit_tag("Get Entitlements", :class => "get_ent") %></td>
      </tr>


    </table>

<% end %>



<%= form_tag("/entitlementsfile", :id => 'file_form', :method => "post", :multipart => true) do %>



    <table class="form_table">
      <tr>
        <td><%= label_tag(:partyid, "") %></td>
        <td><%= file_field_tag 'upload_file', :type => 'file' %></td>
        <td> <%= submit_tag("Entitlements from file", :class => "get_ent_file") %></td>
      </tr>

    </table>

<% end %>

app/views/pages/runquery.html.erb
<h2>Run Query:</h2>

<%= form_tag("/foundbyquery", :id => 'search-form', :method => "get") do %>

    <table>

      <tr>
        <td>   <%= label_tag(:database, "Select database") %> </td>
        <td><%= select_tag(:database, options_for_select([['SAM E04', 'IDMAN6T'], ['SAM E05', 'IDMAN3T'],], 1)) %></td>
        <td></td>
      </tr>



      <tr>
        <td>
          <%= label_tag(:query, "Type your query") %>
        </td>
        <td><%= text_area_tag(:query) %></td>
      </tr>

      <tr>
        <td></td>
        <td><%= submit_tag("Run Query", :class => "run_query") %></td>
        <td></td>
      </tr>

    </table>



<% end %>

app/views/pages/searchusers.html.erb
<h2>Search Users:</h2>

<%= form_tag("/found", :id => 'search-form', :method => "get") do %>

    <table>

      <tr>
        <td>   <%= label_tag(:database, "Select database") %> </td>
        <td><%= select_tag(:database, options_for_select([['SAM E04', 'IDMAN6T'], ['SAM E05', 'IDMAN3T'],], 1)) %></td>
        <td></td>
      </tr>


      <tr>
        <td>
          <%= label_tag(:username, "Username like") %>
        </td>
        <td>
          <%= text_field_tag(:username) %>
        </td>
      </tr>


      <tr>
        <td>
          <%= label_tag(:date, "Date created") %>
        </td>
        <td>
          <%= text_field_tag(:date) %>
        </td>
      </tr>


      <tr>
        <td>
          <%= label_tag(:entitlement, "Entitlement") %>
        </td>
        <td><%= text_field_tag(:entitlement) %></td>
      </tr>

      <tr>
        <td></td>
        <td><%= submit_tag("Run Query", :class => "run_query") %></td>
        <td></td>
      </tr>

    </table>



<% end %>

app/views/users/getusers.html.erb
<h1>Get Users:</h1>


<%= form_tag("/found", :method => "get") do %>

    <%= label_tag(:username, "Username like:") %>
  <%= text_field_tag(:username) %><br>
  <%= label_tag(:date, "Date created:") %>
  <%= text_field_tag(:date) %><br>
    <%= label_tag(:entitlement, "Entilement:") %>
  <%= text_field_tag(:entitlement) %><br>


  <%= submit_tag("Search") %>
<% end %>